import fs from 'node:fs'
import path from 'node:path'
import { describe, expect, it } from 'vitest'

const modalComponentPath = path.resolve(__dirname, '../../components/MiniappModal.tsx')
const modalStylesPath = path.resolve(__dirname, '../../components/MiniappModal.scss')
const pawMenuStylesPath = path.resolve(__dirname, 'MiniappPawMenu.scss')
const pawMenuPath = path.resolve(__dirname, 'MiniappPawMenu.tsx')
const gamesModalPath = path.resolve(__dirname, 'MiniappGamesModal.tsx')
const meViewPath = path.resolve(__dirname, 'MiniappMeView.tsx')
const mbtiPath = path.resolve(__dirname, 'MiniappMbtiTest.tsx')
const avatarEditorPath = path.resolve(__dirname, 'MiniappAvatarEditor.tsx')
const memoryPanelPath = path.resolve(__dirname, 'MiniappMemoryPanel.tsx')
const codewordModalPath = path.resolve(__dirname, 'MiniappCodewordModal.tsx')
const tarotFlowStylesPath = path.resolve(__dirname, '../tarot/MiniappTarotFlow.scss')

describe('miniapp ui presentation rules', () => {
  it('provides a shared centered modal with an image close button in the top-right corner', () => {
    const component = fs.readFileSync(modalComponentPath, 'utf8')
    const styles = fs.readFileSync(modalStylesPath, 'utf8')

    expect(component).toContain('MiniappModal')
    expect(component).toContain('miniapp-modal__close')
    expect(component).toContain('modal-close.png')
    expect(styles).toContain('.miniapp-modal {')
    expect(styles).toContain('align-items: center;')
    expect(styles).toContain('.miniapp-modal__close {')
    expect(styles).toContain('top: 24rpx;')
    expect(styles).toContain('right: 24rpx;')
    expect(styles).not.toMatch(/\.miniapp-modal__panel[^{]*\{[^}]*inset: auto 0 0/)
  })

  it('keeps the paw print quick menu as the only allowed bottom drawer', () => {
    const styles = fs.readFileSync(pawMenuStylesPath, 'utf8')

    expect(styles).toMatch(/\.miniapp-paw-menu__sheet/)
  })

  it('presents MBTI, contact, about and avatar editing through the shared modal', () => {
    expect(fs.readFileSync(mbtiPath, 'utf8')).toContain('<MiniappModal')
    const meView = fs.readFileSync(meViewPath, 'utf8')
    expect(meView).toContain('<MiniappModal')
    expect(meView).toContain('联系我们')
    expect(meView).toContain('关于小多利')
    expect(meView).toContain('setAboutOpen(true)')
    expect(meView).toContain('仅此一只')
    expect(meView).toContain('老实巴交')
    expect(meView).toContain('等妈妈回家')
    expect(meView).toContain('miniapp-about__version')
    expect(fs.readFileSync(avatarEditorPath, 'utf8')).toContain('<MiniappModal')
    expect(fs.readFileSync(memoryPanelPath, 'utf8')).toContain('<MiniappModal')
  })

  it('right-aligns the about modal version line', () => {
    const styles = fs.readFileSync(path.resolve(__dirname, 'MiniappMeView.scss'), 'utf8')
    expect(styles).toContain('.miniapp-about__version {')
    expect(styles).toMatch(/\.miniapp-about__version \{[^}]*text-align: right;/)
  })

  it('presents the games hub through the shared modal with gobang and a coming-soon hint', () => {
    const gamesModal = fs.readFileSync(gamesModalPath, 'utf8')

    expect(gamesModal).toContain('<MiniappModal')
    expect(gamesModal).toContain('五子棋')
    expect(gamesModal).toContain('gobang.png')
    expect(gamesModal).toContain('敬请期待')
  })

  it('shows codeword, game and tarot icon entries in the paw menu and removes the footprint map entry', () => {
    const menu = fs.readFileSync(pawMenuPath, 'utf8')

    expect(menu).toContain('codeword.png')
    expect(menu).toContain('game.png')
    expect(menu).toContain('tarot.png')
    expect(menu).toContain('onOpenCodeword(): void')
    expect(menu).toContain('onOpenGames(): void')
    expect(menu).not.toContain('足迹地图')
    expect(menu).not.toContain('onOpenMap')
    expect(menu).not.toContain('entry-caption')
  })

  it('uses a hand-painted MBTI icon in the personal settings list', () => {
    const meView = fs.readFileSync(meViewPath, 'utf8')

    expect(meView).toContain('mbti.png')
    expect(meView).not.toContain('miniapp-me__mbti-icon')
  })

  it('presents the daily codeword through the shared centered modal', () => {
    const modal = fs.readFileSync(codewordModalPath, 'utf8')

    expect(modal).toContain('<MiniappModal')
    expect(modal).toContain('每日暗号')
    expect(modal).toContain('answerCodeword')
  })

  it('keeps tarot history as a centered themed panel instead of a bottom drawer', () => {
    const styles = fs.readFileSync(tarotFlowStylesPath, 'utf8')

    expect(styles).toContain('.miniapp-tarot-history__panel')
    expect(styles).not.toContain('miniapp-tarot-history__sheet')
  })

  it('uses the letter-paper asset for the nest empty-friend letter card', () => {
    const component = fs.readFileSync(path.resolve(__dirname, 'MiniappNestLetter.tsx'), 'utf8')
    const styles = fs.readFileSync(path.resolve(__dirname, 'MiniappNestLetter.scss'), 'utf8')
    const nestView = fs.readFileSync(path.resolve(__dirname, 'MiniappNestView.tsx'), 'utf8')
    const manifest = fs.readFileSync(path.resolve(__dirname, '../../../../docs/assets/asset-manifest.json'), 'utf8')

    expect(nestView).toContain('<MiniappNestLetter')
    expect(nestView).toContain('记录你和小多利的共同生活。')
    expect(component).toContain('letter-paper.png')
    expect(component).toContain('<XiaoduoliBoxScene')
    expect(component).not.toContain('empty-puppy.png')
    expect(component).not.toContain('empty-dog-bed.png')
    expect(component).not.toContain('empty-dog-house.png')
    expect(component).not.toContain('empty-plant-large.png')
    expect(component).not.toContain('empty-toy-ball.png')
    expect(component).toContain("mode=\"widthFix\"")
    expect(component).toContain('nest-letter__paper')
    expect(component).toContain('给还没来的家人：')
    expect(styles).toContain('.nest-letter__paper')
    expect(styles).not.toContain('.nest-letter__plant')
    expect(styles).toContain('.nest-letter__body')
    expect(manifest).toContain('nest/letter-paper.png')
    expect(manifest).not.toContain('nest/empty-puppy.png')
    expect(manifest).not.toContain('nest/empty-plant-large.png')
  })

  it('presents the journal tab with sliced puppy photos and photo-replace actions', () => {
    const component = fs.readFileSync(path.resolve(__dirname, 'MiniappJournalView.tsx'), 'utf8')
    const styles = fs.readFileSync(path.resolve(__dirname, 'MiniappJournalView.scss'), 'utf8')
    const editor = fs.readFileSync(path.resolve(__dirname, '../../pages/journal-editor/journal-editor.tsx'), 'utf8')
    const editorStyles = fs.readFileSync(path.resolve(__dirname, '../../pages/journal-editor/journal-editor.scss'), 'utf8')
    const manifest = fs.readFileSync(path.resolve(__dirname, '../../../../docs/assets/asset-manifest.json'), 'utf8')

    expect(component).toContain('polaroid-run.png')
    expect(component).toContain('action-write.png')
    expect(component).toContain('action-photo.png')
    expect(component).toContain('journalDisplayPhotos')
    expect(component).toContain('replaceTodayPhoto')
    expect(component).toContain('拍照记录')
    expect(component).toContain('记录和小多利的每一天。')
    expect(component).toContain('查看 >')
    expect(component).toContain('<JournalAnniversaryPanel')
    expect(component).not.toContain('toggleLike')
    expect(component).not.toContain('onShareTitleChange')
    expect(component).not.toContain('openType="share"')
    expect(component).not.toContain('journal-anniversary/journal-anniversary')
    expect(styles).toContain('.journal-today__polaroid')
    expect(styles).toContain('.miniapp-journal__week-card')
    expect(styles).toMatch(/\.miniapp-journal \{[^}]*background: #fff8ee/)
    expect(styles).not.toContain('linear-gradient(180deg, #fffdf7')
    expect(styles).toMatch(/\.miniapp-journal__week-card \{[^}]*padding: 24rpx 18rpx 16rpx/)
    expect(styles).toMatch(/\.miniapp-journal \{[^}]*--journal-gap: 32rpx/)
    expect(styles).toMatch(/\.miniapp-journal \{[^}]*min-height: calc\(100vh - 220px\)/)
    expect(styles).toMatch(/\.miniapp-journal__title \{[^}]*text-align: left;/)
    expect(styles).toMatch(/\.miniapp-journal__tabs \{[^}]*justify-content: center;/)
    expect(styles).toMatch(/\.journal-today__action-art \{[^}]*width: 112rpx/)
    expect(styles).toMatch(/\.journal-today \{[^}]*padding: 24rpx 22rpx 18rpx/)
    expect(styles).toMatch(/\.journal-today__stage \{[^}]*min-height: 256rpx/)
    expect(styles).toMatch(/\.miniapp-journal \{[^}]*padding: 4px 28px 2px/)
    expect(styles).not.toMatch(/\.journal-today \{[^}]*flex: 1/)
    expect(styles).toMatch(/\.miniapp-journal__fortune \{[^}]*padding: 22rpx 24rpx/)
    expect(styles).not.toMatch(/\.miniapp-journal__fortune \{[^}]*margin-top: auto/)
    expect(styles).toContain('-webkit-line-clamp: 3')
    expect(component).toContain('<JournalEditorForm')
    expect(component).not.toContain('journal-editor/journal-editor')
    expect(fs.readFileSync(path.resolve(__dirname, '../../pages/journal-editor/journal-editor.config.ts'), 'utf8')).toContain('#fff8ee')
    expect(editor).toContain('JournalEditorForm')
    const form = fs.readFileSync(path.resolve(__dirname, 'JournalEditorForm.tsx'), 'utf8')
    const formStyles = fs.readFileSync(path.resolve(__dirname, 'JournalEditorForm.scss'), 'utf8')
    expect(form).toContain('polaroid-run.png')
    expect(form).toContain('replacePrimaryPhoto')
    expect(form).toContain('editor-yard.jpg')
    expect(form).toContain('写日记')
    expect(form).toContain('天气')
    expect(form).toContain('心情')
    expect(form).toContain('相册')
    expect(form).toContain('地点')
    expect(form).not.toContain('puppy-cushion.png')
    expect(formStyles).toContain('.journal-editor__yard')
    expect(formStyles).toContain('.journal-editor__card')
    expect(formStyles).toContain('.journal-editor__nav')
    expect(formStyles).toContain('.journal-editor__toolbar')
    expect(editorStyles).toContain('background: #fff8ee')
    expect(editorStyles).not.toContain('puppy-cushion')
    expect(manifest).toContain('journal/polaroid-run.png')
    expect(manifest).toContain('journal/polaroid-sit.png')
    expect(manifest).toContain('journal/action-photo.png')
    expect(manifest).toContain('journal/action-write.png')
    expect(manifest).toContain('journal/editor-yard.jpg')
  })

  it('presents the message tab empty state with an invite illustration and share action', () => {
    const component = fs.readFileSync(path.resolve(__dirname, 'MiniappMessagesView.tsx'), 'utf8')
    const styles = fs.readFileSync(path.resolve(__dirname, 'MiniappMessagesView.scss'), 'utf8')
    const manifest = fs.readFileSync(path.resolve(__dirname, '../../../../docs/assets/asset-manifest.json'), 'utf8')

    expect(component).toContain('messages-empty.png')
    expect(component).not.toContain('messages-plant.png')
    expect(component).toContain('hasFriendConversations')
    expect(component).toContain('你们的每一句温暖都由小多帮您记住')
    expect(component).toContain('搜索好友并通过后，这里会显示你们的聊天。')
    expect(component).toContain('去邀请好友')
    expect(component).toContain('openType="share"')
    expect(component).toContain("mode=\"widthFix\"")
    expect(styles).not.toContain('.miniapp-messages__plant')
    expect(styles).toContain('.miniapp-messages__empty-card')
    expect(styles).toContain('.miniapp-messages__empty-illustration')
    expect(styles).toMatch(/\.miniapp-messages__empty-illustration \{[^}]*width:\s*360px;/)
    expect(styles).toMatch(/\.miniapp-messages__empty-illustration \{[^}]*margin-bottom:\s*20px;/)
    expect(styles).toContain('.miniapp-messages__empty-action')
    expect(styles).toMatch(/\.miniapp-messages__empty-action \{[^}]*linear-gradient/)
    expect(manifest).toContain('messages-empty.png')
    expect(manifest).not.toContain('messages-plant.png')
  })

  it('shows a locked box scene and unlock button after a friend accepts the invitation', () => {
    const nestView = fs.readFileSync(path.resolve(__dirname, 'MiniappNestView.tsx'), 'utf8')
    const scene = fs.readFileSync(path.resolve(__dirname, 'XiaoduoliBoxScene.tsx'), 'utf8')
    const styles = fs.readFileSync(path.resolve(__dirname, 'XiaoduoliBoxScene.scss'), 'utf8')
    const indexPage = fs.readFileSync(path.resolve(__dirname, '../../pages/index/index.tsx'), 'utf8')
    const manifest = fs.readFileSync(path.resolve(__dirname, '../../../../docs/assets/asset-manifest.json'), 'utf8')

    expect(nestView).toContain('<MiniappNestLetter')
    expect(nestView).toContain("sceneMode === 'empty' || sceneMode === 'locked'")
    expect(indexPage).toContain('getNestActionButton')
    expect(indexPage).toContain("nestAction.kind === 'unlock'")
    expect(scene).not.toContain('UNLOCK_BUTTON_LABEL')
    expect(scene).not.toContain('room-background.webp')
    expect(scene).toContain('xiaoduoli-box.png')
    expect(scene).toContain('xiaoduoli-peek.png')
    expect(scene).not.toContain('xiaoduoli-box-idle.png')
    expect(scene).not.toContain('xiaoduoli-box-front.png')
    expect(scene).not.toContain('xiaoduoli-box-body.png')
    expect(scene).not.toContain('xiaoduoli-idle-00.png')
    expect(scene).not.toContain('getBoxIdleFrameIndex')
    expect(scene).toContain('createUnlockEffects')
    expect(styles).toContain('@keyframes xiaoduoli-peek')
    expect(styles).toContain('xiaoduoli-peek 3.2s ease-in-out infinite')
    expect(styles).not.toContain('@keyframes xiaoduoli-peek-body')
    expect(styles).not.toContain('@keyframes xiaoduoli-breathe')
    expect(styles).toContain('@keyframes xiaoduoli-jump')
    expect(styles).toContain('@keyframes xiaoduoli-ribbon')
    expect(styles).toContain('@media (prefers-reduced-motion: reduce)')
    expect(manifest).toContain('nest/xiaoduoli-box.png')
    expect(manifest).toContain('nest/xiaoduoli-peek.png')
    expect(manifest).not.toContain('nest/xiaoduoli-box-idle.png')
    expect(manifest).not.toContain('nest/xiaoduoli-box-front.png')
    expect(manifest).not.toContain('nest/xiaoduoli-idle-00.png')
  })
})
